services:
    application:
        class: Camspiers\PhpLibCreate\Console\Application
    create_command:
        class: Camspiers\PhpLibCreate\Command\CreateCommand
        tags:
            - { name: application.command }
    create_github_command:
        class: Camspiers\PhpLibCreate\Command\CreateGithubCommand
        arguments:
            - @github_client
        tags:
            - { name: application.command }
    init_command:
        class: Composer\Command\InitCommand
        tags:
            - { name: application.command }
    dialog_helper:
        class: Composer\Command\Helper\DialogHelper
        tags:
            - { name: application.helper }
    github_client:
        class: Github\Client
